# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created: Fri May 02 23:19:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWin(object):
    def setupUi(self, mainWin):
        mainWin.setObjectName(_fromUtf8("mainWin"))
        mainWin.resize(1100, 600)
        mainWin.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWin.setWindowIcon(icon)
        mainWin.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        mainWin.setIconSize(QtCore.QSize(48, 48))
        mainWin.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralWidget = QtGui.QWidget(mainWin)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setMargin(1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolButtonImport = QtGui.QToolButton(self.centralWidget)
        self.toolButtonImport.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonImport.setIcon(icon1)
        self.toolButtonImport.setIconSize(QtCore.QSize(36, 36))
        self.toolButtonImport.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolButtonImport.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonImport.setAutoRaise(True)
        self.toolButtonImport.setObjectName(_fromUtf8("toolButtonImport"))
        self.verticalLayout.addWidget(self.toolButtonImport)
        self.toolButtonAppend = QtGui.QToolButton(self.centralWidget)
        self.toolButtonAppend.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/addfile.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAppend.setIcon(icon2)
        self.toolButtonAppend.setIconSize(QtCore.QSize(36, 36))
        self.toolButtonAppend.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolButtonAppend.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonAppend.setAutoRaise(True)
        self.toolButtonAppend.setObjectName(_fromUtf8("toolButtonAppend"))
        self.verticalLayout.addWidget(self.toolButtonAppend)
        self.toolButtonExport = QtGui.QToolButton(self.centralWidget)
        self.toolButtonExport.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/foldermove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonExport.setIcon(icon3)
        self.toolButtonExport.setIconSize(QtCore.QSize(36, 35))
        self.toolButtonExport.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolButtonExport.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonExport.setAutoRaise(True)
        self.toolButtonExport.setObjectName(_fromUtf8("toolButtonExport"))
        self.verticalLayout.addWidget(self.toolButtonExport)
        self.tableView = QtGui.QTableView(self.centralWidget)
        self.tableView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableView.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setShowGrid(True)
        self.tableView.setGridStyle(QtCore.Qt.NoPen)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tableView.horizontalHeader().setDefaultSectionSize(120)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setDefaultSectionSize(40)
        self.verticalLayout.addWidget(self.tableView)
        self.filterLayout = QtGui.QGridLayout()
        self.filterLayout.setSpacing(6)
        self.filterLayout.setObjectName(_fromUtf8("filterLayout"))
        self.filterEdit = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterEdit.sizePolicy().hasHeightForWidth())
        self.filterEdit.setSizePolicy(sizePolicy)
        self.filterEdit.setStyleSheet(_fromUtf8(""))
        self.filterEdit.setObjectName(_fromUtf8("filterEdit"))
        self.filterLayout.addWidget(self.filterEdit, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.filterLayout.addItem(spacerItem, 0, 7, 1, 1)
        self.filterCloseButton = QtGui.QToolButton(self.centralWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterCloseButton.setIcon(icon4)
        self.filterCloseButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.filterCloseButton.setAutoRaise(True)
        self.filterCloseButton.setObjectName(_fromUtf8("filterCloseButton"))
        self.filterLayout.addWidget(self.filterCloseButton, 0, 1, 1, 1)
        self.filterCaseBox = QtGui.QCheckBox(self.centralWidget)
        self.filterCaseBox.setObjectName(_fromUtf8("filterCaseBox"))
        self.filterLayout.addWidget(self.filterCaseBox, 0, 4, 1, 1)
        self.filterOptionButton = QtGui.QToolButton(self.centralWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/find1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterOptionButton.setIcon(icon5)
        self.filterOptionButton.setIconSize(QtCore.QSize(16, 16))
        self.filterOptionButton.setCheckable(True)
        self.filterOptionButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.filterOptionButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.filterOptionButton.setAutoRaise(True)
        self.filterOptionButton.setArrowType(QtCore.Qt.NoArrow)
        self.filterOptionButton.setObjectName(_fromUtf8("filterOptionButton"))
        self.filterLayout.addWidget(self.filterOptionButton, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(5, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.filterLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.filterLayout)
        self.filterLine = QtGui.QFrame(self.centralWidget)
        self.filterLine.setFrameShape(QtGui.QFrame.HLine)
        self.filterLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.filterLine.setObjectName(_fromUtf8("filterLine"))
        self.verticalLayout.addWidget(self.filterLine)
        self.rowIndicator = QtGui.QLabel(self.centralWidget)
        self.rowIndicator.setFrameShape(QtGui.QFrame.StyledPanel)
        self.rowIndicator.setFrameShadow(QtGui.QFrame.Sunken)
        self.rowIndicator.setAlignment(QtCore.Qt.AlignCenter)
        self.rowIndicator.setObjectName(_fromUtf8("rowIndicator"))
        self.verticalLayout.addWidget(self.rowIndicator)
        mainWin.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(mainWin)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        mainWin.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(mainWin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        mainWin.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(mainWin)
        self.toolBar.setEnabled(True)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        mainWin.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionImport = QtGui.QAction(mainWin)
        self.actionImport.setIcon(icon1)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionExit = QtGui.QAction(mainWin)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(mainWin)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/infoabout.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExport = QtGui.QAction(mainWin)
        self.actionExport.setIcon(icon3)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionFilter = QtGui.QAction(mainWin)
        self.actionFilter.setIcon(icon5)
        self.actionFilter.setObjectName(_fromUtf8("actionFilter"))
        self.actionAppend = QtGui.QAction(mainWin)
        self.actionAppend.setIcon(icon2)
        self.actionAppend.setObjectName(_fromUtf8("actionAppend"))
        self.actionHelp = QtGui.QAction(mainWin)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon8)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionSettings = QtGui.QAction(mainWin)
        self.actionSettings.setEnabled(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/configure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon9)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionDeleteRow = QtGui.QAction(mainWin)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/cut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRow.setIcon(icon10)
        self.actionDeleteRow.setObjectName(_fromUtf8("actionDeleteRow"))
        self.actionResizeRowsToContents = QtGui.QAction(mainWin)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Bloomy/textfile.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeRowsToContents.setIcon(icon11)
        self.actionResizeRowsToContents.setObjectName(_fromUtf8("actionResizeRowsToContents"))
        self.actionResizeRows = QtGui.QAction(mainWin)
        self.actionResizeRows.setObjectName(_fromUtf8("actionResizeRows"))
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionAppend)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFilter)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menu_Help.addAction(self.actionAbout)
        self.menu_Help.addAction(self.actionHelp)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.actionFilter)
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(mainWin)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.close)
        QtCore.QObject.connect(self.actionImport, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onImport)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onAbout)
        QtCore.QObject.connect(self.actionExport, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onExport)
        QtCore.QObject.connect(self.actionFilter, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onFilter)
        QtCore.QObject.connect(self.filterEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), mainWin.onFilterInput)
        QtCore.QObject.connect(self.filterCloseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWin.onFilter)
        QtCore.QObject.connect(self.actionAppend, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onImport)
        QtCore.QObject.connect(self.filterCaseBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), mainWin.onFilterCaseState)
        QtCore.QObject.connect(self.actionHelp, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onHelp)
        QtCore.QObject.connect(self.actionSettings, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onSettings)
        QtCore.QObject.connect(self.toolButtonImport, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionImport.trigger)
        QtCore.QObject.connect(self.toolButtonExport, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionExport.trigger)
        QtCore.QObject.connect(self.toolButtonAppend, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionAppend.trigger)
        QtCore.QObject.connect(self.actionDeleteRow, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onDeleteRow)
        QtCore.QObject.connect(self.actionResizeRowsToContents, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onResizeRowsToContents)
        QtCore.QObject.connect(self.actionResizeRows, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWin.onResizeRows)
        QtCore.QMetaObject.connectSlotsByName(mainWin)
        mainWin.setTabOrder(self.tableView, self.filterCloseButton)
        mainWin.setTabOrder(self.filterCloseButton, self.filterOptionButton)
        mainWin.setTabOrder(self.filterOptionButton, self.filterEdit)
        mainWin.setTabOrder(self.filterEdit, self.filterCaseBox)

    def retranslateUi(self, mainWin):
        mainWin.setWindowTitle(_translate("mainWin", "DaleyKlippings", None))
        self.toolButtonImport.setToolTip(_translate("mainWin", "Import notes", None))
        self.toolButtonImport.setStatusTip(_translate("mainWin", "Import...", None))
        self.toolButtonImport.setText(_translate("mainWin", "&Import", None))
        self.toolButtonAppend.setToolTip(_translate("mainWin", "Append highlights, notes, and bookmarks", None))
        self.toolButtonAppend.setStatusTip(_translate("mainWin", "Append...", None))
        self.toolButtonAppend.setText(_translate("mainWin", "&Append", None))
        self.toolButtonExport.setToolTip(_translate("mainWin", "Export notes", None))
        self.toolButtonExport.setStatusTip(_translate("mainWin", "Export...", None))
        self.toolButtonExport.setText(_translate("mainWin", "&Export", None))
        self.filterEdit.setPlaceholderText(_translate("mainWin", "Filter", None))
        self.filterCloseButton.setText(_translate("mainWin", "...", None))
        self.filterCaseBox.setText(_translate("mainWin", "Case &sensitive", None))
        self.filterOptionButton.setText(_translate("mainWin", "▼", None))
        self.rowIndicator.setText(_translate("mainWin", "Rows: 0/0", None))
        self.menuFile.setTitle(_translate("mainWin", "&File", None))
        self.menu_Help.setTitle(_translate("mainWin", "&Help", None))
        self.toolBar.setWindowTitle(_translate("mainWin", "Show tool bar", None))
        self.actionImport.setText(_translate("mainWin", "&Import...", None))
        self.actionImport.setToolTip(_translate("mainWin", "Import highlights, notes, and bookmarks", None))
        self.actionImport.setStatusTip(_translate("mainWin", "Load clippings...", None))
        self.actionImport.setShortcut(_translate("mainWin", "Ctrl+I", None))
        self.actionExit.setText(_translate("mainWin", "E&xit", None))
        self.actionExit.setToolTip(_translate("mainWin", "Close application", None))
        self.actionExit.setStatusTip(_translate("mainWin", "Exit", None))
        self.actionExit.setShortcut(_translate("mainWin", "Ctrl+X", None))
        self.actionAbout.setText(_translate("mainWin", "About", None))
        self.actionAbout.setToolTip(_translate("mainWin", "Info about Klippings", None))
        self.actionAbout.setStatusTip(_translate("mainWin", "About Klippings", None))
        self.actionExport.setText(_translate("mainWin", "&Export...", None))
        self.actionExport.setToolTip(_translate("mainWin", "Export edited highlights, notes, and bookmarks", None))
        self.actionExport.setStatusTip(_translate("mainWin", "Export notes...", None))
        self.actionExport.setShortcut(_translate("mainWin", "Ctrl+E", None))
        self.actionFilter.setText(_translate("mainWin", "&Filter", None))
        self.actionFilter.setToolTip(_translate("mainWin", "Filter the table", None))
        self.actionFilter.setStatusTip(_translate("mainWin", "Filter...", None))
        self.actionFilter.setShortcut(_translate("mainWin", "Ctrl+F", None))
        self.actionAppend.setText(_translate("mainWin", "&Append...", None))
        self.actionAppend.setToolTip(_translate("mainWin", "Append current list of hilghlights, notes, and bookmarks", None))
        self.actionAppend.setStatusTip(_translate("mainWin", "Append clippings...", None))
        self.actionAppend.setShortcut(_translate("mainWin", "Ctrl+A", None))
        self.actionHelp.setText(_translate("mainWin", "&Help", None))
        self.actionHelp.setIconText(_translate("mainWin", "Help", None))
        self.actionHelp.setToolTip(_translate("mainWin", "Open help webpage in your brouser", None))
        self.actionHelp.setStatusTip(_translate("mainWin", "Help webpage...", None))
        self.actionHelp.setShortcut(_translate("mainWin", "Ctrl+H", None))
        self.actionSettings.setText(_translate("mainWin", "&Settings...", None))
        self.actionSettings.setToolTip(_translate("mainWin", "Configure settings", None))
        self.actionSettings.setStatusTip(_translate("mainWin", "Settings...", None))
        self.actionSettings.setShortcut(_translate("mainWin", "Ctrl+S", None))
        self.actionDeleteRow.setText(_translate("mainWin", "&Delete selected rows", None))
        self.actionDeleteRow.setShortcut(_translate("mainWin", "Del", None))
        self.actionResizeRowsToContents.setText(_translate("mainWin", "&Resize rows to contents", None))
        self.actionResizeRowsToContents.setShortcut(_translate("mainWin", "Ctrl+R", None))
        self.actionResizeRows.setText(_translate("mainWin", "Re&size rows...", None))
        self.actionResizeRows.setShortcut(_translate("mainWin", "Ctrl+Alt+R", None))

import mainWin_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWin = QtGui.QMainWindow()
    ui = Ui_mainWin()
    ui.setupUi(mainWin)
    mainWin.show()
    sys.exit(app.exec_())

